local _M = {}

_M.template = [=[
# This is a wholesale copy of the activate command generated by `virtualenv`[1]
# Many thanks to go Ian Bicking and that team for making such a fine piece of
# software That I find it necessary to build myself similar tools for lua.  This
#
# [1] http://www.virtualenv.org/
#
# file must be used with "source bin/activate" *from your shell* you cannot run
# it directly

deactivate () {
    if [[ -n "$_OLD_VERT_PATH" ]]
    then
        PATH=$_OLD_VERT_PATH
        export PATH
        unset _OLD_VERT_PATH
    fi

    if [[ -n "$_OLD_VERT_PS1" ]]
    then
        PS1=$_OLD_VERT_PS1
        export PS1
        unset _OLD_VERT_PS1
    fi

    if [[ -n "$_OLD_LUA_PATH" ]]
        LUA_PATH=$_OLD_VERT_LUA_PATH
        export LUA_PATH
        unset _OLD_VERT_LUA_PATH
    then
        unset LUA_PATH
    fi

    if [[ -n "$_OLD_LUA_CPATH" ]]
        LUA_CPATH=$_OLD_VERT_LUA_CPATH
        export LUA_CPATH
        unset _OLD_VERT_LUA_CPATH
    then
        unset LUA_CPATH
    fi

    unset LUA_VERSION
    unset VERT

    # This should detect bash and zsh, which have a hash command that must
    # be called to get it to forget past commands.  Without forgetting
    # past commands the $PATH changes we made may not be respected
    if [[ -n "$BASH" ]] || [[ -n "$ZSH_VERSION" ]]
    then
        hash -r
    fi

    if [ ! "$1" = "nondestructive" ]
    then
        # Self destruct!
        unset -f deactivate
    fi
}

deactivate nondestructive

LUA_VERSION="%s"
VERT="%s"

export LUA_VERSION
export VERT

if [[ -z "$VERT_DISABLE_PROMPT" ]]
then
    _OLD_VERT_PS1="$PS1"
    export _OLD_VERT_PS1

    if [[ "x" != x ]]
    then
        PS1="$PS1"
    else
        PS1="(`basename \"$VERT\"`)$PS1"
    fi

    export PS1
fi


if [[ -n "$LUA_PATH" ]]
then
    _OLD_VERT_LUA_PATH=$LUA_PATH
    export _OLD_VERT_LUA_PATH
fi

if [[ -n "$LUA_CPATH" ]]
then
    _OLD_VERT_LUA_CPATH=$LUA_CPATH
    export _OLD_VERT_LUA_CPATH
fi

if [[ -n "$PATH" ]]
then
    _OLD_VERT_PATH=$PATH
    export _OLD_VERT_PATH
fi

LUA_PATH="./?.lua;$VERT/share/lua/$LUA_VERSION/?.lua;$VERT/share/lua/$LUA_VERSION/?/init.lua;$VERT/lib/lua/$LUA_VERSION/?.lua;$VERT/lib/lua/$LUA_VERSION/?/init.lua"
LUA_CPATH="./?.so;$VERT/lib/lua/$LUA_VERSION/?.so;$VERT/lib/lua/$LUA_VERSION/loadall.so"
PATH="$VERT/bin:$PATH"

export LUA_PATH
export LUA_CPATH
export PATH

# This should detect bash and zsh, which have a hash command that must
# be called to get it to forget past commands.  Without forgetting
# past commands the $PATH changes we made may not be respected
if [[ -n "$BASH" ]] || [[ -n "$ZSH_VERSION" ]] ; then
    hash -r
fi
]=]

function _M.write(lua_version, prefix)
  local activate_file, err = io.open(prefix.."/bin/activate", "w+")

  if not activate_file then
    print("Failed to open activate file: "..err)
    os.exit(3)
  end

  activate_file:write(string.format(_M.template, lua_version, prefix))
  activate_file:close()
end

return _M
